/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MySkillsRouteImport } from './routes/my-skills'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestRequestIdRouteImport } from './routes/request.$requestId'
import { Route as CommunityNewRouteImport } from './routes/community.new'
import { Route as CommunityPostIdRouteImport } from './routes/community.$postId'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MySkillsRoute = MySkillsRouteImport.update({
  id: '/my-skills',
  path: '/my-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRequestIdRoute = RequestRequestIdRouteImport.update({
  id: '/request/$requestId',
  path: '/request/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityNewRoute = CommunityNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityPostIdRoute = CommunityPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => CommunityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRouteWithChildren
  '/directory': typeof DirectoryRoute
  '/my-skills': typeof MySkillsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/community/new': typeof CommunityNewRoute
  '/request/$requestId': typeof RequestRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRouteWithChildren
  '/directory': typeof DirectoryRoute
  '/my-skills': typeof MySkillsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/community/new': typeof CommunityNewRoute
  '/request/$requestId': typeof RequestRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRouteWithChildren
  '/directory': typeof DirectoryRoute
  '/my-skills': typeof MySkillsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/community/new': typeof CommunityNewRoute
  '/request/$requestId': typeof RequestRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/community'
    | '/directory'
    | '/my-skills'
    | '/sitemap.xml'
    | '/submit'
    | '/community/$postId'
    | '/community/new'
    | '/request/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/community'
    | '/directory'
    | '/my-skills'
    | '/sitemap.xml'
    | '/submit'
    | '/community/$postId'
    | '/community/new'
    | '/request/$requestId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/community'
    | '/directory'
    | '/my-skills'
    | '/sitemap.xml'
    | '/submit'
    | '/community/$postId'
    | '/community/new'
    | '/request/$requestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  DirectoryRoute: typeof DirectoryRoute
  MySkillsRoute: typeof MySkillsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubmitRoute: typeof SubmitRoute
  RequestRequestIdRoute: typeof RequestRequestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-skills': {
      id: '/my-skills'
      path: '/my-skills'
      fullPath: '/my-skills'
      preLoaderRoute: typeof MySkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/$requestId': {
      id: '/request/$requestId'
      path: '/request/$requestId'
      fullPath: '/request/$requestId'
      preLoaderRoute: typeof RequestRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/new': {
      id: '/community/new'
      path: '/new'
      fullPath: '/community/new'
      preLoaderRoute: typeof CommunityNewRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/$postId': {
      id: '/community/$postId'
      path: '/$postId'
      fullPath: '/community/$postId'
      preLoaderRoute: typeof CommunityPostIdRouteImport
      parentRoute: typeof CommunityRoute
    }
  }
}

interface CommunityRouteChildren {
  CommunityPostIdRoute: typeof CommunityPostIdRoute
  CommunityNewRoute: typeof CommunityNewRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityPostIdRoute: CommunityPostIdRoute,
  CommunityNewRoute: CommunityNewRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CommunityRoute: CommunityRouteWithChildren,
  DirectoryRoute: DirectoryRoute,
  MySkillsRoute: MySkillsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubmitRoute: SubmitRoute,
  RequestRequestIdRoute: RequestRequestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
